function out = make_csplines(knotvec)

out{length(knotvec) + 1} = [];

delvec = diff(knotvec);

out{1} = @(x) ( ...
        subplus(x - knotvec(1)) .^ 2 / 2 - ...
        ( ...
            subplus(x - knotvec(1)) .^ 3 - subplus(x - knotvec(2)) .^ 3 ...
        ) / (6 * delvec(1)) ...
    ) * (2 / (delvec(1)));

for(index = 2:(length(knotvec)-1))
    out{index} = @(x) ( ...
        ( ...
            subplus(x - knotvec(index-1)) .^ 3 - subplus(x - knotvec(index)) .^ 3 ...
        ) / (6 * delvec(index-1)) - ...
        ( ...
            subplus(x - knotvec(index)) .^ 3 - subplus(x - knotvec(index+1)) .^ 3 ...
        ) / (6 * delvec(index)) ...
    ) * (2 / (delvec(index-1) + delvec(index)));

end

endindex = length(knotvec);
out{endindex} = @(x) ( ...
        ( ...
            subplus(x - knotvec(endindex-1)) .^ 3 - subplus(x - knotvec(endindex)) .^ 3 ... 
        ) / (6 * delvec(endindex-1)) - ...
        subplus(x - knotvec(endindex)) .^ 2 / 2 ...
    ) * (2 / (delvec(endindex-1)));

out{endindex + 1} = @(x) x;
out{endindex + 2} = @(x) ones(size(x));

end
